### ISSUE TITLE
Issue regarding settings.php being ignored

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/b#205]
When Bee executes, it loads _settings.php_ at the following line of code:

miscellaneous.inc: Line 57:  `backdrop_settings_initialize();`

After this code executes, `backdrop_bootstrap()` is called which re-executes `backdrop_settings_initialize()` and attempts to re-initializes _settings.php_ but does not succeed because Backdrop loads _settings.php_ using `require_once`.

This resets global `$settings` to an empty array and any code that refers to `$settings` will return empty or `NULL`.

The fix is to change line 57 to invoke `backdrop_bootstrap(BACKDROP_BOOTSTRAP_CONFIGURATION);`

This will employ `backdrop_boostrap()` to only load the configuration phase and prevent it from being re-executed later because backdrop will ignore phases that have previously ran.

**Comment by rbargerhuff** [comment]
So our fix failed the workflow test that is in place and @smaiorana and I believe it concerns the handling of multisites. Unfortunately our institution does not implement multisites.

We request help because this issue we feel it is critical.

Edit: We converted our current site to a multisite using the bare minimum for testing purposes and we were unable to replicate the error being thrown by the test workflow. The test workflow is erroring during the Multisite tests and one of the commands, `bee status`, is returning something that the test is not expecting.

When we execute this command, it correctly reports `Multisite`.

**Comment by indigoxela** [comment]
@rbargerhuff I think the test crash isn't actually related to the current change.

```
TypeError: Argument 2 passed to PHPUnit\Framework\Assert::assertRegExp() must be of the type string, null given...
```
PHP nags that NULL is not a string (as expected). Casting to `(string)` seems to fix that.

**Comment by rbargerhuff** [comment]
Thank you so much for your response. That is a huge relief.

**Comment by yorkshire-pudding** [comment]
@rbargerhuff - Thanks for this and the PR.  Please could you give some examples of the functions affected by this bug so I can test and hopefully get this merged?

**Comment by smaiorana** [comment]
@yorkshire-pudding - @rbargerhuff and I are currently converting a Drupal 7 website to work with Backdrop. We define custom configuration options in settings.php that our in-house modules use and reference. When we attempted to clear the cache using Bee, we found that the those config values were unavailable. We traced it back to the issue that @rbargerhuff submitted a PR to fix. We don't have a specific function to provide, but one way to test is to set custom `cache_backends` - those are definitely not honored when Bee clears the cache.

**Comment by yorkshire-pudding** [comment]
@BWPanda - please can you review this request and PR?  Without a clear function to test, I think it boils down to whether the fix they are proposing can cause issues elsewhere.  I don't understand the code well enough to know if there are implications here.

**Comment by yorkshire-pudding** [comment]
@rbargerhuff and @smaiorana 
I have fixed the issues in test that were causing your earlier error and now we are getting errors for Multisite that are not present on the current version.

Tests failing are all under multisite
✘ Site global option works
✘ Install command works
✘ Download command works

<details>
<summary>Test results</summary>

```bash
PHPUnit 8.5.30 #StandWithUkraine

Bee Core
 ✔ Bee is installed correctly
 ✔ Unknown command triggers an error
 ✔ Missing required argument triggers an error
 ✔ Commands can be called via an alias
 ✔ Root global option works
 ✔ Yes global option works
 ✔ Debug global option works

Cache Commands
 ✔ Cache clear command works

Config Commands
 ✔ Config get command works
 ✔ Config set command works
 ✔ Config export command works
 ✔ Config import command works

Cron Commands
 ✔ Cron command works

DBCommands
 ✔ Db export command works
 ✔ Db import command works

DBLog Commands
 ✔ Log command works

Download Commands
 ✔ Download command works
 ✔ Download core command works

Help Commands
 ✔ Help command works

PHPCommands
 ✔ Eval command works

Projects Commands
 ✔ Projects command works
 ✔ Enable command works
 ✔ Disable command works
 ✔ Uninstall command works
 ✔ Theme default command works
 ✔ Theme admin command works

Update Commands
 ✔ Update db command works

User Commands
 ✔ Users command works
 ✔ User password command works
 ✔ User login command works

Time: 40.86 seconds, Memory: 12.00 MB

OK (30 tests, 89 assertions)
PHPUnit 8.5.30 #StandWithUkraine

Multisite
 ✘ Site global option works
   ┐
   ├ Failed asserting that '' matches PCRE pattern "/Site type +Multisite/".
   │
   ╵ /app/tests/multisite/MultisiteTest.php:20
   ┴

Multisite Install Commands
 ✘ Install command works
   ┐
   ├ Failed asserting that '' matches PCRE pattern "/Site type +Multisite/".
   │
   ╵ /app/tests/multisite/MultisiteInstallCommandsTest.php:17
   ┴

Multisite Download Commands
 ✘ Download command works
   ┐
   ├ Failed asserting that '' contains "'simplify' was downloaded into '/app/multisite/modules/simplify'.".
   │
   ╵ /app/tests/multisite/MultisiteDownloadCommandsTest.php:17
   ┴

Time: 249 ms, Memory: 10.00 MB


FAILURES!
Tests: 3, Assertions: 3, Failures: 3.
```
</details>

If I manually try to download simplify it silently fails which is why the test is then failing:
```bash
user@HOST:~/projects/bee/multisite$ lando bee dl simplify
user@HOST:~/projects/bee/multisite$ ll modules/
total 12
drwxr-xr-x  2 shl shl 4096 Oct  6 09:49 ./
drwxr-xr-x 10 shl shl 4096 Oct  6 09:49 ../
-rw-r--r--  1 shl shl 1602 Oct  6 09:49 README.md
user@HOST:~/projects/bee/multisite$
```

**Comment by yorkshire-pudding** [comment]
@rbargerhuff @smaiorana - what happens when you select `Home` > `Flush all caches` from the admin bar in the front end.
Ultimately `bee` calls `backdrop_flush_all_caches` which is also what the admin bar calls.

**Comment by quicksketch** [comment]
> We don't have a specific function to provide, but one way to test is to set custom cache_backends - those are definitely not honored when Bee clears the cache.

I ran into this exact problem while porting [memcache](https://github.com/backdrop-contrib/memcache). As @rbargerhuff describes, everything in the `$settings` array gets discarded if a command specifies a `bootstrap` level.

I also confirmed that changing the line suggested in https://github.com/rbargerhuff/bee/commit/82dba077da6100e716056d414328f643f28f7000 solves the problem, since this notifies Backdrop that the bootstrap level 0 has been executed, and `settings.php` has already been included.

I believe that bee only works right now because a lot of the values in the `$settings` array are copied out into other places, like the database connection gets copied into `$database`. But because `backdrop_settings_initialize()` specifically sets `$settings = array()` and then follows it with a `require_once()` (which has already been executed), `$settings` ends up empty on all `bee` CLI commands.

**Comment by indigoxela** [comment]
@rbargerhuff the test crash you noticed should be fixed in the meantime - mind to rebase your PR to confirm everything works now?

**Comment by yorkshire-pudding** [comment]
@quicksketch @indigoxela @rbargerhuff @smaiorana 
I tested the PR after fixing the PHP 8.1 related errors and it is still failing the multisite tests - see my results [here](https://github.com/backdrop-contrib/bee/issues/205#issuecomment-1269631208)

If anyone has any insight as to why this change would break multisite, I'm open to solutions so this change can be made.

**Comment by indigoxela** [comment]
Hm, not sure... each site in a multisite setup has its own settings.php - maybe there's a mixup? Seems unlikely, though.

@yorkshire-pudding did you mix up the links? Your "here" doesn't provide the info I expected. :wink:

**Comment by yorkshire-pudding** [comment]
@indigoxela - yes - must have copied and pasted wrong. Fixed now.

**Comment by indigoxela** [comment]
@yorkshire-pudding is that the main directory of your install? `/projects/bee/multisite`

Try `cd sites/one-of-your-multi` - if running bee, you're supposed to do that in the directory, the active settings.php is in. (That's different than drush does it.)

**Comment by yorkshire-pudding** [comment]
@indigoxela - That's not quite right.  You can download from there and it downloads into the shared modules folder.
When enabling, you need to do `bee --site=one-of-your-multi en module_name`
If you're downloading just for one site you need to do `bee --site=one-of-your-multi dl module_name`; it doesn't matter where you are when you do download, without site argument it goes to the shared.

**Comment by indigoxela** [comment]
Ah, got it, I mixed that with `bee st`... downloading is more flexible.

Yes, confirmed, the PR breaks multisite `dl`.

To be more clear: when one cd's to the directory containing the settings.php, bee dl works (puts the module into that sites dir).
But without that patch, it also works from the main directory - with the patch that's broken.

**Comment by rbargerhuff** [comment]
Hello there. I was just wondering where things currently stand with this issue? I understand that our fix revealed a flaw in the logic associated with Multisite. As it stands my colleague and I do not have the experience needed in order to fix the Multisite logic ourselves.

**Comment by yorkshire-pudding** [comment]
@rbargerhuff 
Hi Rick. I'm afraid that I also am at a loss as to how to fix this; I can't implement your PR as it breaks multisite but this is obviously causing you issues.  I've looked through the code but I can't understand why this breaks multisite.

@quicksketch @BWPanda @klonos - are any of you able to help with this?

**Comment by indigoxela** [comment]
We keep running into issues with backdrop_settings_initialize() running twice - which causes the problem with empty settings and lost overrides.
What happens has been described several times (in different issues), but we have no strategy yet, how to fix that.

Switching the default to BACKDROP_BOOTSTRAP_CONFIGURATION seems like a problematic approach to me.

**Comment by yorkshire-pudding** [comment]
For completeness, here are the other issues (and the link to the start of the mention) where this occurs:
- https://github.com/backdrop-contrib/bee/issues/84#issuecomment-1285151631
- https://github.com/backdrop-contrib/bee/issues/61#issuecomment-808902429

@rbargerhuff @smaiorana - I don't think you ever answered this question; please can you answer. I want to ensure this is not just an issue with the `backdrop_flush_all_caches` which `bee` has no control over.

>  - what happens when you select `Home` > `Flush all caches` from the admin bar in the front end. Ultimately `bee` calls `backdrop_flush_all_caches` which is also what the admin bar calls.

**Comment by rbargerhuff** [comment]
@yorkshire-pudding At the time @smaiorana and I originally submitted this issue, we specifically remember that when we cleared the cache via `Home`  > `Flush all caches` from the admin bar, the issue did not occur. It was *only* when we tried to use `bee` to clear the cache,  did the issue occur.

This was observed by us and @quicksketch for the same reason. We were attempting to port the Drupal Memcache module so that it would work with Backdrop. When we defined `cache_backends` in `settings.php` the setting was ignored by `bee`. 

We specifically and successfully verified that the `$settings` array that contains the custom settings read from `settings.php` was in fact empty after `bee` executed ` backdrop_settings_initialize()` a second time.

It is safe to say any custom settings or overrides added to `settings.php` *will* be ignored.

This is why we insist that this issue is a *Major* issue.

**Comment by quicksketch** [comment]
Although I don't particularly like it as a solution, I think `bee` could work around the wiping out of `$settings` by copying the value of `$settings` before calling `backdrop_bootstrap()` and then restore it afterwards.

Core changes might help: either don't wipe out `$settings` in `backdrop_settings_initialize()` or allow including `settings.php` multiple times. Both seem potentially fraught though.

I think overall #206 is the right approach for reading in the `settings.php` values, but I haven't looked into how to get it working with multisite yet.

**Comment by yorkshire-pudding** [comment]
> @yorkshire-pudding At the time @smaiorana and I originally submitted this issue, we specifically remember that when we cleared the cache via `Home` > `Flush all caches` from the admin bar, the issue did not occur. It was _only_ when we tried to use `bee` to clear the cache, did the issue occur.

Thank you for confirming this.

> This was observed by us and @quicksketch for the same reason. We were attempting to port the Drupal Memcache module so that it would work with Backdrop. When we defined `cache_backends` in `settings.php` the setting was ignored by `bee`.

Thank you for clarifying what you were trying to do.

> We specifically and successfully verified that the `$settings` array that contains the custom settings read from `settings.php` was in fact empty after `bee` executed ` backdrop_settings_initialize()` a second time.
> 
> It is safe to say any custom settings or overrides added to `settings.php` _will_ be ignored.
>
> This is why we insist that this issue is a _Major_ issue.

It may be a major issue for you, but `bee` is not broken for the majority of users and therefore in the context of the `bee` issue queue, it is not a major issue, hence why I renamed it.

I would like to see a resolution to this but your proposed fix causes a major issue for multisite users, which is not acceptable.  There are some multisite actions that can only be done via the command line so implementing your 'fix' would cause significant problems for multisite users.

I have spent many hours looking at this and trying to find a solution, but I have not yet worked out how to fix this without breaking `bee` for others.

I have reached out to more experienced developers to ask for support, but none has been forthcoming (I see @quicksketch has just responded), except from @indigoxela . We discussed this at length on Wednesday during Office Hours, but were unable to find a solution.  

I would suggest in the short to medium term, you look at patching your installation of `bee` to reflect the change that works for you until such time as we can get some more assistance on this.

**Comment by yorkshire-pudding** [comment]
@rbargerhuff 
Hi Rick
Following @quicksketch 's suggestion of saving the settings, I have implemented a mechanism that does this.  It works for multisite and passes all the tests.  I don't have enough information to recreate your conditions, so I would be grateful for you to test this PR.
Thanks

**Comment by indigoxela** [comment]
@yorkshire-pudding great progress!

I tested locally with bee dl and multisite and can confirm that it works. :+1: I also tried different commands that require a higher bootstrap level (like `ws`) and put a var_dump before and after the restore in miscellaneous.inc, and can confirm that settings are back. WFM!

I ran into an edge case, though. On one of the testing sites the Feeds module is installed, which adds a setting to the global settings via hook_boot() (cache_class_cache_feeds_http), and that setting is there in the global $settings before restore, but is lost after the restore.

We might be able to catch that with array_merge (and eventually array_unique).
Example: `$settings = array_merge($_bee_settings, $settings);`

**Comment by yorkshire-pudding** [comment]
> We might be able to catch that with array_merge (and eventually array_unique).
> Example: `$settings = array_merge($_bee_settings, $settings);`

Good idea. PR updated.

**Comment by indigoxela** [comment]
Hm... just thinking this over. Right before backdrop_bootstrap() the settings are still intact, so it would be sufficient to just create a quick temporary variable inside function bee_bootstrap() to play back previous settings right after backdrop_bootstrap() has flushed them. Or am I missing something?

I played with a minimal change:
```php
  if (!empty($_bee_backdrop_root) && function_exists('backdrop_bootstrap')) {
    global $settings;
    $settings_initial = $settings;
    backdrop_bootstrap($level);
    $settings = array_unique(array_merge($settings_initial, $settings));
```
And it seems to do the trick. No extra global var needed.

**Comment by yorkshire-pudding** [comment]
Thanks I tried something similar earlier but hadn't declared $settings as global so it didn't work.  I tried the other way and it worked and I forgot to go back.  PR updated.

**Comment by indigoxela** [comment]
That's great, it works! :+1:

Curious, if this also works for @rbargerhuff and @smaiorana.

**Comment by smaiorana** [comment]
I tried the new PR from @yorkshire-pudding and the `bee cc all` commands breaks for us. The problems seems to be the use of `array_unique` to clean the `$settings` array. It's wiping out any array elements with similar values.

If I strip out the use of `array_unique` and simply use `array_merge`, it works.

So this change does resolve our issue (same as @indigoxela sans the use of `array_unique`):

```
  if (!empty($_bee_backdrop_root) && function_exists('backdrop_bootstrap')) {
    global $settings;
    $settings_initial = $settings;
    backdrop_bootstrap($level);
    $settings = array_merge($settings_initial, $settings);
```

Is there any reason that `array_unique` would be necessary?

**Comment by yorkshire-pudding** [comment]
Thanks for testing @smaiorana . I've removed `array_unique`.  Please test again.

**Comment by smaiorana** [comment]
Tested and it works!

**Comment by yorkshire-pudding** [comment]
Great. Thanks for testing. I'll get this merged tomorrow.

**Comment by indigoxela** [comment]
@smaiorana could you provide a var_dump of your $settings variable after merge? What you describe makes me think that you end up with multiple declarations of the same setting, which might not be what we want.

I did test config override from settings.php, BTW, and it works properly for me - tested with a site_name override.

**Comment by yorkshire-pudding** [comment]
Looking at the definition of `array_unique` and doing some testing on this I can understand that if you have several boolean values or even integers, there is a strong chance that they would clash and the latter would be taken out. It works just on values, not on keys or combination of keys and values.

Take this test.  With `array_unique` and `backdrop_drupal_compatibility` set to false (the same as `update_free_access`):

```php
array(5) {
  ["update_free_access"]=>
  bool(false)
  ["hash_salt"]=>
  string(43) "59SypqLifRBeXwbjiRwnOC0jiqjASkoY-PhlSHxUReU"
  ["404_fast_paths_exclude"]=>
  string(34) "/\/(?:styles)|(?:system\/files)\//"
  ["404_fast_paths"]=>
  string(69) "/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i"
  ["404_fast_html"]=>
  string(162) "<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>"
}
```

and without `array_unique`:

```php
array(6) {
  ["update_free_access"]=>
  bool(false)
  ["hash_salt"]=>
  string(43) "59SypqLifRBeXwbjiRwnOC0jiqjASkoY-PhlSHxUReU"
  ["404_fast_paths_exclude"]=>
  string(34) "/\/(?:styles)|(?:system\/files)\//"
  ["404_fast_paths"]=>
  string(69) "/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i"
  ["404_fast_html"]=>
  string(162) "<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>"
  ["backdrop_drupal_compatibility"]=>
  bool(false)
}
```

Note that with `array_unique`, `backdrop_drupal_compatibility` disappears as although it has a different key, it has the same value as `update_free_access`.

**Comment by yorkshire-pudding** [comment]
Thanks to @indigoxela and @quicksketch for help in identifying the fix and refining the solution.

**Comment by quicksketch** [comment]
Thanks @yorkshire-pudding!
